# --- pybrickz ---
$env.DNA_METASTORE_PASSWORD = 'REDACTED'

# --- azure devops ---
$env.AZURE_ARTIFACTS_TOKEN = 'REDACTED'
$env.AZURE_DEV_OPS_TOKEN_TIBORSTANKO = 'REDACTED'
$env.AZURE_DEV_OPS_TOKEN_ZNA_PREDICTIVE_ANALYTICS = 'REDACTED'
$env.AZURE_DEV_OPS_TOKEN = $env.AZURE_DEV_OPS_TOKEN_ZNA_PREDICTIVE_ANALYTICS
$env.AZURE_DEVOPS_EXT_PAT = $env.AZURE_DEV_OPS_TOKEN_ZNA_PREDICTIVE_ANALYTICS

# --- zurich llm lounge ---
$env.ZURICHAT_CLIENT_ID = "REDACTED"
$env.ZURICHAT_CLIENT_SECRET = "REDACTED"
$env.ZURICHAT_API_KEY = "REDACTED"

# --- claude code (using zurich llms) ---
$env.ANTHROPIC_AUTH_TOKEN = 'REDACTED'
$env.ANTHROPIC_BASE_URL = 'REDACTED'
$env.ANTHROPIC_DEFAULT_HAIKU_MODEL = 'us.anthropic.claude-haiku-4-5-20251001-v1:0'
$env.ANTHROPIC_DEFAULT_OPUS_MODEL = 'us.anthropic.claude-opus-4-6-v1'
$env.ANTHROPIC_DEFAULT_SONNET_MODEL = 'us.anthropic.claude-sonnet-4-6'
$env.ANTHROPIC_MODEL = $env.ANTHROPIC_DEFAULT_OPUS_MODEL
$env.CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS = 1

# --- github (zna) ---
$env.GITHUB_TOKEN = 'REDACTED'

# --- databricks ---
$env.DATABRICKS_CLIENT_ID = "REDACTED"
$env.DATABRICKS_CLIENT_SECRET = "REDACTED"
$env.DATABRICKS_HOST = "REDACTED"